import os
from datetime import date, datetime
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from supabase import Client, create_client

load_dotenv()

app = FastAPI()

# Supabase setup
url: str = os.environ.get("SUPABASE_ENDPOINT")
# Use service role key to bypass RLS policies
key: str = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)

TABLE_NAME = os.environ.get("TABLE_NAME")


class PolicySearchRequest(BaseModel):
    claimant_first_name: Optional[str] = None
    claimant_last_name: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    policy_number: Optional[str] = None


class VehicleSearchRequest(BaseModel):
    vin: str
    policy_number: str


class TriageRequest(BaseModel):
    claim_number: str
    first_name: str
    last_name: str


class ServiceProviderSearchRequest(BaseModel):
    provider_type: str


class HistoricalClaimSearchRequest(BaseModel):
    policy_number: str


class Triage(BaseModel):
    claimid: str
    financial_severity: Optional[int] = None
    injury_severity: Optional[int] = None
    complexity_score: Optional[int] = None
    final_severity_score: Optional[int] = None
    severity_label: Optional[str] = None
    fraud_indicators: Optional[bool] = False
    fraud_notes: Optional[str] = None
    historical_claims_found: Optional[bool] = False
    adjuster_id: Optional[str] = None
    adjuster_name: Optional[str] = None
    adjuster_email: Optional[str] = None
    adjuster_phone: Optional[str] = None
    adjuster_license_state: Optional[str] = None
    adjuster_specializations: Optional[list[str]] = None
    adjuster_current_caseload: Optional[int] = None
    adjuster_caseload_capacity: Optional[int] = None
    adjuster_customer_satisfaction: Optional[float] = None
    first_contact_sla: Optional[date] = None
    inspection_deadline: Optional[date] = None
    coverage_decision_timeline: Optional[date] = None
    payment_target_timeline: Optional[date] = None
    closure_timeline: Optional[date] = None
    priority_level: Optional[str] = None
    next_required_actions: Optional[list[str]] = None
    triage_notes: Optional[str] = None
    summary_completed: Optional[bool] = False


class Claim(BaseModel):
    claim_number: Optional[str] = None
    claim_status: Optional[str] = None
    created_timestamp: Optional[datetime] = None
    report_date: Optional[date] = None
    policy_number: Optional[str] = None
    claimant_first_name: Optional[str] = None
    claimant_last_name: Optional[str] = None
    claimant_phone: Optional[str] = None
    claimant_email: Optional[str] = None
    vehicle_vin: Optional[str] = None
    vehicle_year: Optional[int] = None
    vehicle_make: Optional[str] = None
    vehicle_model: Optional[str] = None
    loss_date: Optional[date] = None
    loss_location: Optional[str] = None
    loss_type: Optional[str] = None
    injury_involved: Optional[bool] = None
    police_report_filed: Optional[bool] = None
    accident_description: Optional[str] = None
    adjuster_id: Optional[str] = None
    coverage_confirmed: Optional[bool] = None
    deductible_amount: Optional[float] = None
    subrogation_potential: Optional[bool] = None
    triage_completed: Optional[datetime] = None
    first_contact_date: Optional[datetime] = None
    inspection_completed: Optional[datetime] = None
    damage_assessment: Optional[float] = None
    repair_authorized: Optional[bool] = None
    repair_shop_name: Optional[str] = None
    payment_amount: Optional[float] = None
    payment_date: Optional[datetime] = None
    subrogation_demand_sent: Optional[bool] = None
    claim_closed_date: Optional[datetime] = None
    closure_reason: Optional[str] = None
    cycle_time_days: Optional[int] = None
    customer_satisfaction: Optional[float] = None
    image_url: Optional[str] = None


@app.get("/claims", response_model=list[Claim])
async def get_claims():
    """
    Retrieve all claims from the Supabase table.
    """
    response = supabase.table(TABLE_NAME).select("*").execute()
    if response.data:
        return response.data
    return []


@app.get("/claims/{claim_number}", response_model=Claim)
async def get_claim(claim_number: str):
    """
    Retrieve a specific claim by claim number.
    """
    response = (
        supabase.table(TABLE_NAME)
        .select("*")
        .eq("claim_number", claim_number)
        .execute()
    )
    if response.data and len(response.data) > 0:
        return response.data[0]
    raise HTTPException(status_code=404, detail=f"Claim {claim_number} not found.")


@app.post("/claims", response_model=Claim)
async def create_claim(claim: Claim):
    """
    Create a new claim in the Supabase table.
    claim_number will be auto-generated by the database.
    """
    # Exclude unset fields and claim_number from the request
    claim_data = claim.dict(exclude_unset=True, exclude_none=True)

    # Remove claim_number if present (should be auto-generated)
    if "claim_number" in claim_data:
        del claim_data["claim_number"]

    # Filter out empty strings and placeholder values like "string"
    filtered_data = {}
    for key, value in claim_data.items():
        # Skip empty strings and common placeholder values
        if isinstance(value, str) and (value == "" or value.lower() == "string"):
            continue
        # Convert datetime and date objects to ISO format
        if isinstance(value, (datetime, date)):
            filtered_data[key] = value.isoformat()
        else:
            filtered_data[key] = value

    response = supabase.table(TABLE_NAME).insert(filtered_data).execute()
    if response.data:
        return response.data[0]
    raise HTTPException(status_code=400, detail="Claim could not be created.")


@app.delete("/claims/{claim_number}", response_model=dict)
async def delete_claim(claim_number: str):
    """
    Delete a claim from the Supabase table by claim_number.
    """
    response = (
        supabase.table(TABLE_NAME).delete().eq("claim_number", claim_number).execute()
    )
    if response.data:
        return {"message": f"Claim {claim_number} deleted successfully."}
    raise HTTPException(status_code=404, detail=f"Claim {claim_number} not found.")


@app.post("/policies/search", response_model=list[dict])
async def search_policies(search_params: PolicySearchRequest):
    """
    Search for policies using:
    - Claimant full name (first and last name)
    - Contact information (phone or email)
    - Policy number

    At least one search parameter must be provided.
    Returns all matching policy rows from the policies table.
    """
    # Validate that at least one parameter is provided
    if not any(
        [
            search_params.claimant_first_name,
            search_params.claimant_last_name,
            search_params.phone,
            search_params.email,
            search_params.policy_number,
        ]
    ):
        raise HTTPException(
            status_code=400, detail="At least one search parameter must be provided"
        )

    # Build the query
    query = supabase.table("policies").select("*")

    if search_params.policy_number:
        query = query.eq("policy_number", search_params.policy_number)

    if search_params.claimant_first_name:
        query = query.ilike(
            "named_insured_first", f"%{search_params.claimant_first_name}%"
        )

    if search_params.claimant_last_name:
        query = query.ilike(
            "named_insured_last", f"%{search_params.claimant_last_name}%"
        )

    if search_params.phone:
        query = query.eq("named_insured_phone", search_params.phone)

    if search_params.email:
        query = query.ilike("named_insured_email", f"%{search_params.email}%")

    # Execute policy query
    response = query.execute()

    if not response.data:
        raise HTTPException(
            status_code=404, detail="No policies found matching the criteria"
        )

    return response.data


@app.post("/vehicles/search", response_model=dict)
async def search_vehicle(search_params: VehicleSearchRequest):
    """
    Fetch a specific vehicle record using VIN and policy number.
    Returns the complete vehicle data row.
    """
    response = (
        supabase.table("vehicles")
        .select("*")
        .eq("vin", search_params.vin)
        .eq("policy_number", search_params.policy_number)
        .execute()
    )

    if not response.data or len(response.data) == 0:
        raise HTTPException(
            status_code=404,
            detail=f"Vehicle with VIN {search_params.vin} and policy number {search_params.policy_number} not found",
        )

    return response.data[0]


@app.get("/triagefetch", response_model=list[Claim])
async def get_latest_claims_for_triage():
    """
    Fetch the latest 6 claims where adjuster_id is empty/null.
    Returns claims ordered by created_timestamp in descending order.
    """
    response = (
        supabase.table(TABLE_NAME)
        .select("*")
        .is_("adjuster_id", "null")
        .order("created_timestamp", desc=True)
        .limit(6)
        .execute()
    )

    if response.data:
        return response.data
    return []


@app.post("/fortriage", response_model=Claim)
async def get_claim_for_triage(triage_params: TriageRequest):
    """
    Fetch claim details for triage using claim number, first name, and last name.
    Returns the claim details if all parameters match.
    """
    response = (
        supabase.table(TABLE_NAME)
        .select("*")
        .eq("claim_number", triage_params.claim_number)
        .eq("claimant_first_name", triage_params.first_name)
        .eq("claimant_last_name", triage_params.last_name)
        .execute()
    )

    if not response.data or len(response.data) == 0:
        raise HTTPException(
            status_code=404,
            detail=f"Claim not found with the provided claim number and claimant name",
        )

    return response.data[0]


@app.get("/adjusters", response_model=list[dict])
async def get_adjusters():
    """
    Retrieve all adjusters from the adjusters table.
    """
    response = supabase.table("adjusters").select("*").execute()
    if response.data:
        return response.data
    return []


@app.post("/historical-claims/search", response_model=list[dict])
async def search_historical_claims(search_params: HistoricalClaimSearchRequest):
    """
    Fetch historical claims based on policy_number.
    Returns all historical claims associated with the given policy number.
    """
    response = (
        supabase.table("historical_claims")
        .select("*")
        .eq("policy_number", search_params.policy_number)
        .execute()
    )

    if not response.data:
        raise HTTPException(
            status_code=404,
            detail=f"No historical claims found for policy_number: {search_params.policy_number}",
        )

    return response.data


@app.post("/triage", response_model=dict)
async def create_triage(triage: Triage):
    """
    Create a new triage record in the triage table.
    The claimid must reference an existing claim_number from the claims table.
    """
    # Exclude unset fields and none values
    triage_data = triage.dict(exclude_unset=True, exclude_none=True)

    # Filter out empty strings and placeholder values like "string"
    filtered_data = {}
    for key, value in triage_data.items():
        # Skip empty strings and common placeholder values
        if isinstance(value, str) and (value == "" or value.lower() == "string"):
            continue
        # Convert date objects to ISO format
        if isinstance(value, date):
            filtered_data[key] = value.isoformat()
        else:
            filtered_data[key] = value

    # Validate that claimid is provided
    if "claimid" not in filtered_data:
        raise HTTPException(status_code=400, detail="claimid is required")

    response = supabase.table("triage").insert(filtered_data).execute()
    if response.data:
        return response.data[0]
    raise HTTPException(status_code=400, detail="Triage record could not be created.")


@app.post("/service-providers/search", response_model=list[dict])
async def search_service_providers(search_params: ServiceProviderSearchRequest):
    """
    Search for service providers by provider_type.
    Returns all matching service provider records.
    """
    # Execute query
    response = (
        supabase.table("service_providers")
        .select("*")
        .eq("provider_type", search_params.provider_type)
        .execute()
    )

    if not response.data:
        raise HTTPException(
            status_code=404,
            detail=f"No service providers found with provider_type: {search_params.provider_type}",
        )

    return response.data


@app.put("/fortriage/{claim_number}", response_model=Claim)
async def update_claim_for_triage(claim_number: str, claim: Claim):
    """
    Update claim data for triage using claim number.
    Only updates the fields that are provided in the request.
    Protected fields (claim_number, first name, last name, policy_number) cannot be modified.
    """
    # Exclude unset fields, none values, and claim_number from update
    update_data = claim.dict(exclude_unset=True, exclude_none=True)

    # List of protected fields that cannot be updated
    protected_fields = [
        "claim_number",
        "claimant_first_name",
        "claimant_last_name",
        "claimant_phone",
        "claimant_email",
        "policy_number",
        "vehicle_vin",
    ]

    # Remove protected fields from update
    for field in protected_fields:
        if field in update_data:
            del update_data[field]

    # Filter out empty strings and placeholder values like "string"
    filtered_data = {}
    for key, value in update_data.items():
        # Skip empty strings and common placeholder values
        if isinstance(value, str) and (value == "" or value.lower() == "string"):
            continue
        # Convert datetime and date objects to ISO format
        if isinstance(value, (datetime, date)):
            filtered_data[key] = value.isoformat()
        else:
            filtered_data[key] = value

    if not filtered_data:
        raise HTTPException(
            status_code=400, detail="No valid fields provided for update"
        )

    # Update the claim
    response = (
        supabase.table(TABLE_NAME)
        .update(filtered_data)
        .eq("claim_number", claim_number)
        .execute()
    )

    if not response.data or len(response.data) == 0:
        raise HTTPException(status_code=404, detail=f"Claim {claim_number} not found")

    return response.data[0]


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app)
